# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170712_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='learn_times',
            new_name='learn_time',
        ),
    ]
